Fix compile bugs after rebase
Change in error.cc fixes:

> libdrizzle/error.cc:44:10: error: enumeration value
'DRIZZLE_RETURN_MAX' not handled in switch
[-Werror=switch-enum] switch (arg)