Bugfix: Fix check for c++11 support
Letting autoconf include AX_CXX_COMPILE_STDCXX
automatically to check the C++ compiler for c++11 support
did not work correctly.
Thus the file ax_cxx_compile_stdcxx.m4 has been added

Fixes the error which was reported in #62:
error: 'long long' is a C++11 extension [-Werror,-Wc++11-long-long]