Avoid blocking in drizzle_connect()
if the connection is set to nonblocking.
Instead of calling connect_poll() in the
connecting state, return DRIZZLE_RETURN_IO_WAIT
and push a state which will finish connecting.
In drizzle_connect(), call drizzle_wait()
if the connection is blocking.

This commit also fixes a bug in the original
revision:
http://bazaar.launchpad.net/~wiml-omni/libdrizzle/
nonblocking/revision/132

Please note the change wrt the original revision,
which fixes the compile error shown below.

<   if (getnameinfo(aip->ai_addr, aip->ai_addrlen,
---
>   if (getnameinfo(aip->ai_addr, aip->ai_addr->sa_len,                                                  ^

> libdrizzle/conn.cc:1616:47: error: 'struct sockaddr' has
no member named 'sa_len'
if (getnameinfo(aip->ai_addr, aip->ai_addr->sa_len,